language: ruby
cache: bundler
bundler_args: '-j4'
before_install:
  - "gem update --system"
  - "gem update bundler"
  - "bundle config set without no_ci"
script:
  - "bundle exec rspec"
os:
  - linux
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
matrix:
  include:
    - name: rubocop
      rvm: 2.3
      script: "bundle exec rubocop"
    - name: 'OSX'
      rvm: 2.6
      os: osx
branches:
  only:
    - master
    - v4-stable
